const phones = [
  { id:'1',
    phoneName: "Galaxy S23",
    brand: "Samsung",
    price: "$799",
    url:"https://rukminim2.flixcart.com/image/850/1000/xif0q/mobile/t/0/g/-original-imah4zp7fvqp8wev.jpeg?q=20&crop=false",
    color: "Red",
    battery: "4000mAh",
    screenSize: "6.1 inches",
    ram: "8GB",
    storage: "128GB",
    description: "The Samsung Galaxy S23 combines a sleek design with powerful performance, offering a vibrant 6.1-inch display and a long-lasting 4000mAh battery. With 8GB of RAM and 128GB storage, it's built for speed and efficiency, ideal for multitasking and gaming."
  },
  {id:'2',
    phoneName: "Galaxy Z Fold 5",
    brand: "Samsung",
    price: "$1799",
    color: "Blue",
    battery: "4400mAh",
    screenSize: "7.6 inches",
    ram: "12GB",
    storage: "256GB",
    url:"https://rukminim2.flixcart.com/image/850/1000/xif0q/mobile/y/g/l/-original-imagztmghzuhz7kf.jpeg?q=90&crop=false",
    description: "With its revolutionary foldable design, the Galaxy Z Fold 5 transforms from a 7.6-inch tablet into a compact phone. Its robust 12GB RAM and 256GB storage handle demanding tasks effortlessly, while the 4400mAh battery keeps you going all day."
  },
  {
    id:'3',
    phoneName: "Galaxy A54",
    brand: "Samsung",
    price: "$499",
    color: "Green",
    battery: "5000mAh",
    screenSize: "6.4 inches",
    ram: "6GB",
    storage: "128GB",
    url:"https://rukminim2.flixcart.com/image/850/1000/xif0q/mobile/2/a/t/-original-imagnrhknw9pbg3t.jpeg?q=20&crop=false",
    description: "The Galaxy A54 offers impressive value with a large 6.4-inch display, a powerful 5000mAh battery, and smooth performance. Its 6GB RAM and 128GB storage make it suitable for everyday use and light gaming, perfect for budget-conscious users."
  },
  {
    id:'4',
    phoneName: "Galaxy S23 Ult",
    brand: "Samsung",
    price: "$1199",
    color: "White",
    battery: "5000mAh",
    screenSize: "6.8 inches",
    ram: "12GB",
    storage: "256GB",
    url:"https://rukminim1.flixcart.com/image/300/300/xif0q/mobile/q/k/h/-original-imagzm8qmr7qxfhq.jpeg",
    description: "The Galaxy S23 Ultra is Samsung’s powerhouse, boasting a stunning 6.8-inch display, 12GB RAM, and 256GB storage. With a 5000mAh battery, this phone is built to support intense multitasking, photography, and gaming with ease."
  },
  {
    id:'5',
    phoneName: "iPhone 14 Pro",
    brand: "Apple",
    price: "$999",
    color: "Red",
    battery: "3095mAh",
    screenSize: "6.1 inches",
    ram: "6GB",
    storage: "256GB",
    url:"https://www.jiomart.com/images/product/original/493177801/apple-iphone-14-pro-max-256-gb-silver-digital-o493177801-p593687922-0-202306301844.jpeg?im=Resize=(420,420)",
    description: "Apple’s iPhone 14 Pro delivers a smooth 6.1-inch display and exceptional performance, powered by 6GB RAM and 256GB storage. Its advanced cameras and 3095mAh battery make it a top choice for those who love capturing high-quality photos and videos."
  },
  {
    id:'6',
    phoneName: "iPhone 14",
    brand: "Apple",
    price: "$799",
    color: "Blue",
    battery: "3279mAh",
    screenSize: "6.1 inches",
    ram: "6GB",
    storage: "128GB",
    url:"https://m.media-amazon.com/images/I/61bK6PMOC3L._AC_UF1000,1000_QL80_.jpg",
    description: "The iPhone 14 combines elegance and functionality, with a 6.1-inch display, 3279mAh battery, and 6GB RAM. It provides smooth performance and ample storage at 128GB, perfect for users who prioritize both style and reliability."
  },
  {
    id:'7',
    phoneName: "iPhone 14 Plus",
    brand: "Apple",
    price: "$899",
    color: "Green",
    battery: "4325mAh",
    screenSize: "6.7 inches",
    ram: "6GB",
    storage: "128GB",
    url:"https://ik.imagekit.io/3dqckpw4d/upload/iphone_14_plus_Purple166280821714-plus-purple.png",
    description: "With its large 6.7-inch display and a robust 4325mAh battery, the iPhone 14 Plus is designed for those who need a powerful phone with extended battery life. It includes 6GB RAM and 128GB storage for smooth multitasking and ample space."
  },
  {
    id:'8',
    phoneName: "iPhone SE ",
    brand: "Apple",
    price: "$429",
    color: "White",
    battery: "2018mAh",
    screenSize: "4.7 inches",
    ram: "6GB",
    storage: "64GB",
    url:"https://cellbuddy.in/buddy/wp-content/uploads/2022/11/iPhone-SE-2020-White.jpg",
    description: "Apple's iPhone SE (3rd Gen) is compact yet powerful, with a 4.7-inch display, 6GB RAM, and 64GB storage. It’s ideal for those seeking a smaller, budget-friendly option with reliable performance and essential features."
  },
  {
    id:'9',
    phoneName: "Pixel 8",
    brand: "Google",
    price: "$699",
    color: "Red",
    battery: "4500mAh",
    screenSize: "6.2 inches",
    ram: "8GB",
    storage: "128GB",
    url:"https://www.reliancedigital.in/medias/GoogleGoogle-Pixel-8-494268284-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3w1ODIwMHxpbWFnZS9qcGVnfGltYWdlcy9oYWUvaDJmLzEwMjEyMTQ3MDM2MTkwLmpwZ3w2ZTdjNzk2NzA5YTU2OWYxZTdjODMxOGY2OWNhMzlhM2JkNzM1M2NmY2NlNmU4ZDg3MGFmNWZjMDMwMDMxMWJl",
    description: "Google's Pixel 8 offers a refined Android experience, featuring a 6.2-inch display, 8GB RAM, and 128GB storage. The 4500mAh battery and Google’s software enhancements make it a solid choice for camera and Android enthusiasts alike."
  },
  {
    id:'10',
    phoneName: "Pixel 8 Pro",
    brand: "Google",
    price: "$899",
    color: "Blue",
    battery: "5050mAh",
    screenSize: "6.7 inches",
    ram: "12GB",
    storage: "256GB",
    url:"https://www.designinfo.in/wp-content/uploads/2023/10/Google-Pixel-8-Pro-128GB-Unlocked-Bay-1.webp",
    description: "The Pixel 8 Pro is packed with advanced features, including a 6.7-inch display, 12GB RAM, and 256GB storage. Its 5050mAh battery and AI-powered camera make it an excellent option for photography and media consumption."
  },
  {
    id:'11',
    phoneName: "Pixel 7",
    brand: "Google",
    price: "$599",
    color: "Green",
    battery: "4355mAh",
    screenSize: "6.3 inches",
    ram: "8GB",
    storage: "128GB",
    url:"https://www.designinfo.in/wp-content/uploads/2023/04/Google-Pixel-7-Pro-128GB-Unlocked-Hazel-1-485x603-optimized.jpg",
    description: "Google’s Pixel 7 combines a 6.3-inch display with efficient performance powered by 8GB RAM and 128GB storage. Its 4355mAh battery provides great battery life, while the camera offers superb image quality in various lighting conditions."
  },
  {
    id:'12',
    phoneName: "Pixel 7a",
    brand: "Google",
    price: "$499",
    color: "White",
    battery: "4385mAh",
    screenSize: "6.1 inches",
    ram: "8GB",
    storage: "128GB",
    url:"https://fdn2.gsmarena.com/vv/bigpic/google-pixel-7a.jpg",
    description: "The Pixel 7a offers a balanced experience with its 6.1-inch display, 8GB RAM, and 128GB storage. A solid 4385mAh battery supports all-day use, and Google’s software ensures a smooth, secure user experience."
  },
  {
    id:'13',
    phoneName: "OnePlus 11",
    brand: "OnePlus",
    price: "$649",
    color: "Red",
    battery: "5000mAh",
    screenSize: "6.7 inches",
    ram: "12GB",
    storage: "64GB",
    url: "https://rukminim2.flixcart.com/image/850/1000/xif0q/mobile/v/q/4/11r-5g-5011102671-oneplus-original-imagu5h8x9h8qwrv.jpeg?q=90&crop=false",
    description: "OnePlus 11 delivers strong performance with a 6.7-inch screen, 12GB RAM, and long-lasting 5000mAh battery, perfect for power users."
  },
  {
    id:'14',
    phoneName: "One+ Nord 3",
    brand: "OnePlus",
    price: "$499",
    color: "Blue",
    battery: "4500mAh",
    screenSize: "6.74 inches",
    ram: "8GB",
    storage: "128GB",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIf26ysDBgZtObacJ8XXZuoNvOZefeFIp7VA&s",
    description: "OnePlus Nord 3 offers a great display and smooth experience with 8GB RAM, 128GB storage, and a 4500mAh battery, ideal for multitasking."
  },
  {
    id:'15',
    phoneName: "OnePlus 10 Pro",
    brand: "OnePlus",
    price: "$799",
    color: "Green",
    battery: "5000mAh",
    screenSize: "6.7 inches",
    ram: "12GB",
    storage: "64GB",
    url: "https://cdn1.smartprix.com/rx-iG1bQDedP-w420-h420/oneplus-10-pro-5g.jpg",
    description: "The OnePlus 10 Pro is built for performance with a 6.7-inch display, 12GB RAM, and ample 5000mAh battery, excellent for gaming and productivity."
  },
  {
    id:'16',
    phoneName: "Nord CE 3 Lite",
    brand: "OnePlus",
    price: "$349",
    color: "White",
    battery: "5000mAh",
    screenSize: "6.72 inches",
    ram: "8GB",
    storage: "128GB",
    url: "https://m.media-amazon.com/images/I/61LB+d0vheL._AC_UF1000,1000_QL80_.jpg",
    description: "The Nord CE 3 Lite is a budget-friendly option with 8GB RAM, a big 6.72-inch display, and a 5000mAh battery, ideal for everyday use."
  },
  {
    id:'17',
    phoneName: "Moto G Stylus",
    brand: "Motorola",
    price: "$399",
    color: "Red",
    battery: "5000mAh",
    screenSize: "6.8 inches",
    ram: "6GB",
    storage: "128GB",
    url: "https://images-cdn.ubuy.co.in/665943cd6e634b21cd675483-moto-g-stylus-5g-2024-unlocked.jpg",
    description: "The Moto G Stylus 5G combines a large screen, 6GB RAM, and 5000mAh battery with stylus functionality, making it great for creativity and note-taking."
  },
  {
    id:'18',
    phoneName: "Moto Edge 40",
    brand: "Motorola",
    price: "$599",
    color: "Blue",
    battery: "4600mAh",
    screenSize: "6.55 inches",
    ram: "8GB",
    storage: "64GB",
    url: "https://rukminim2.flixcart.com/image/850/1000/xif0q/mobile/2/m/o/edge-40-pay40030in-motorola-original-imagpqzchzhg6fex.jpeg?q=90&crop=false",
    description: "Moto Edge 40 provides a sleek design with 8GB RAM, 4600mAh battery, and a 6.55-inch display for smooth performance and great visuals."
  },
  {
    id:'19',
    phoneName: "Mi 13 Pro",
    brand: "Xiaomi",
    price: "$749",
    color: "Green",
    battery: "4820mAh",
    screenSize: "6.73 inches",
    ram: "8GB",
    storage: "256GB",
    url: "https://i.gadgets360cdn.com/products/large/xiaomi-13-pro-db-709x800-1670825991.jpg",
    description: "Xiaomi Mi 13 Pro offers flagship features with an expansive 6.73-inch display, 8GB RAM, and 256GB storage, ideal for high-performance tasks."
  },
  {
    id:'20  ',
    phoneName: "Note 12 Pro",
    brand: "Xiaomi",
    price: "$399",
    color: "White",
    battery: "5000mAh",
    screenSize: "6.67 inches",
    ram: "6GB",
    storage: "128GB",
    url: "https://rukminim2.flixcart.com/image/720/864/xif0q/mobile/b/r/f/-original-imaghkvuhzwge3za.jpeg?q=60&crop=false",
    description: "Redmi Note 12 Pro provides solid performance with a 6.67-inch display, 6GB RAM, and 5000mAh battery, making it a great mid-range choice."
  }
  ];
  
  export default phones;